import type {
  AuditEvent,
  BrokerTask,
  BuyerProfile,
  Conversation,
  DealRoom,
  FollowUpDraft,
  MatchResult,
  SellerProfile,
  SellerReportInput,
  VerificationCase,
  YachtListing,
} from "./types";

function listingPhoto(id: string, src: string, alt: string) {
  return [{ id, src, alt }];
}

export const yachtListings: YachtListing[] = [
  {
    id: "listing-aurora-72",
    assetType: "Yacht",
    name: "Aurora 72",
    builder: "Princess",
    model: "Y72",
    year: 2021,
    priceEur: 3_450_000,
    lengthFt: 72,
    cabins: 4,
    engines: "Twin MAN V12 1650",
    engineHours: 690,
    location: "Palma, Mallorca",
    locationLabel: "Palma, Mallorca",
    locationPrecision: "Area",
    coordinates: { lat: 39.5696, lng: 2.6502 },
    vatStatus: "EU VAT Paid",
    availability: "Immediate after survey",
    status: "Active",
    ownerId: "seller-vallon",
    exteriorTone: "White hull with graphite hardtop",
    interiorStyle: "Modern light oak with warm leather",
    refitHistory: ["2025 tender garage refresh", "2024 navigation suite upgrade"],
    highlights: ["EU VAT paid", "Light modern interior", "Stabilizers", "Turnkey Med berth"],
    weaknesses: ["Owner wants fast but firm pricing", "Crew cabin is compact"],
    idealBuyer: "Family buyer wanting a turn-key flybridge with low-friction summer access.",
    documents: [
      { id: "doc-aurora-survey", title: "2026 pre-listing survey", category: "Survey", status: "Approved", updatedAt: "2026-05-13" },
      { id: "doc-aurora-vat", title: "EU VAT certificate", category: "VAT", status: "Approved", updatedAt: "2026-05-10" },
      { id: "doc-aurora-service", title: "MAN service records", category: "Maintenance", status: "Approved", updatedAt: "2026-05-15" },
      { id: "doc-aurora-owner-notes", title: "Seller motivation note", category: "Specs", status: "Internal", updatedAt: "2026-05-18" },
    ],
    comps: [
      { name: "Sunseeker 74 Manhattan 2020", priceEur: 3_600_000, note: "Slightly larger, darker interior." },
      { name: "Ferretti 720 2021", priceEur: 3_550_000, note: "Similar ask, less complete document pack." },
    ],
    faqs: [
      { question: "Is VAT paid?", answer: "Yes, EU VAT certificate is approved.", source: "EU VAT certificate" },
      { question: "Can she be viewed this week?", answer: "Yes, Palma viewing windows are available after broker confirmation.", source: "Broker calendar note" },
    ],
    objections: [
      { buyerId: "buyer-amira-haddad", label: "Crew comfort", detail: "Asked whether crew cabin is too compact for multi-week trips.", raisedAt: "2026-05-18" },
    ],
    missingInfo: ["Owner-approved drone video", "Tender service invoice"],
    ownerNotes: ["Seller prefers qualified family buyers over charter-first buyers."],
    brokerOnlyNotes: ["Seller will consider fast clean terms, but do not disclose flexibility."],
    marketSignals: ["Flybridge inventory in Palma tightened after two May contracts."],
    photos: listingPhoto("photo-aurora-72-main", "/segments/broker-yachts.png", "Aurora 72 yacht in Palma marina"),
    specSummary: "72ft · 4 cabins · 690h · Palma",
    imagePrompt: "Luxury white flybridge yacht at a Palma marina, bright afternoon, realistic brokerage photography",
  },
  {
    id: "listing-palmera-55",
    assetType: "Yacht",
    name: "Palmera F55",
    builder: "Princess",
    model: "F55",
    year: 2019,
    priceEur: 1_390_000,
    lengthFt: 55,
    cabins: 3,
    engines: "Twin Volvo D13",
    engineHours: 520,
    location: "Portals, Mallorca",
    locationLabel: "Portals, Mallorca",
    locationPrecision: "Area",
    coordinates: { lat: 39.5315, lng: 2.5681 },
    vatStatus: "EU VAT Paid",
    availability: "Ready before summer",
    status: "Active",
    ownerId: "seller-vallon",
    exteriorTone: "White hull",
    interiorStyle: "Light oak, neutral fabrics",
    refitHistory: ["2025 upholstery refresh", "2024 generator service"],
    highlights: ["EU VAT paid", "Low engine hours", "Light interior", "Strong family layout"],
    weaknesses: ["No hardtop stabilizers", "Tender is original"],
    idealBuyer: "Buyer seeking a clean 55ft family yacht with fast Med access.",
    documents: [
      { id: "doc-palmera-survey", title: "Condition survey summary", category: "Survey", status: "Approved", updatedAt: "2026-05-16" },
      { id: "doc-palmera-vat", title: "VAT proof", category: "VAT", status: "Approved", updatedAt: "2026-05-11" },
      { id: "doc-palmera-media", title: "Approved image set", category: "Media", status: "Approved", updatedAt: "2026-05-18" },
      { id: "doc-palmera-title", title: "Title extract", category: "Title", status: "Restricted", updatedAt: "2026-05-12" },
    ],
    comps: [
      { name: "Fairline Squadron 53 2018", priceEur: 1_260_000, note: "Lower price, older fit-out." },
      { name: "Ferretti 550 2018", priceEur: 1_420_000, note: "Close substitute with darker interior." },
    ],
    faqs: [
      { question: "How turnkey is she?", answer: "Survey, VAT, and media are approved; tender invoice remains open.", source: "Condition survey summary" },
    ],
    objections: [
      { buyerId: "buyer-daniel-brenner", label: "Stabilizers", detail: "Asked if lack of stabilizers is a blocker for family use.", raisedAt: "2026-05-22" },
    ],
    missingInfo: ["Tender invoice", "Updated oil analysis"],
    ownerNotes: ["Owner wants weekly inquiry quality updates until a second viewing is booked."],
    brokerOnlyNotes: ["Seller is sensitive to low offers below EUR1.32M."],
    marketSignals: ["VAT-paid 55ft family flybridges are moving quickly in Mallorca."],
    photos: listingPhoto("photo-palmera-f55-main", "/segments/broker-yachts.png", "Palmera F55 yacht in Mallorca"),
    specSummary: "55ft · 3 cabins · 520h · Mallorca",
    imagePrompt: "55 foot family yacht in a Mediterranean marina, clean white hull, brokerage photo",
  },
  {
    id: "listing-riva-aqua-63",
    assetType: "Yacht",
    name: "Aqua 63",
    builder: "Riva",
    model: "63 Virtus",
    year: 2018,
    priceEur: 1_950_000,
    lengthFt: 63,
    cabins: 3,
    engines: "Twin MAN V12",
    engineHours: 820,
    location: "Monaco",
    locationLabel: "Monaco",
    locationPrecision: "Area",
    coordinates: { lat: 43.7347, lng: 7.4217 },
    vatStatus: "Commercial",
    availability: "By appointment",
    status: "Pre-Market",
    ownerId: "seller-vallon",
    exteriorTone: "Metallic shark grey",
    interiorStyle: "Gloss walnut and cream",
    refitHistory: ["2025 hull polish", "2023 AV refresh"],
    highlights: ["Iconic brand", "Open Mediterranean layout", "Strong charter story"],
    weaknesses: ["Commercial VAT context needs explanation", "Gloss interior is polarizing"],
    idealBuyer: "Lifestyle buyer wanting brand presence and day-boat theatre.",
    documents: [
      { id: "doc-aqua-spec", title: "Technical spec pack", category: "Specs", status: "Approved", updatedAt: "2026-05-08" },
      { id: "doc-aqua-media", title: "Lifestyle photo set", category: "Media", status: "Approved", updatedAt: "2026-05-19" },
      { id: "doc-aqua-vat", title: "Commercial VAT memo", category: "VAT", status: "Restricted", updatedAt: "2026-05-20" },
    ],
    comps: [
      { name: "Pardo 60 2022", priceEur: 2_100_000, note: "Newer, less iconic brand." },
      { name: "Pershing 62 2017", priceEur: 1_780_000, note: "Sportier, higher hours." },
    ],
    faqs: [
      { question: "Is the VAT position clean?", answer: "Commercial memo exists but must be broker-reviewed before buyer sharing.", source: "Commercial VAT memo" },
    ],
    objections: [],
    missingInfo: ["Broker-approved VAT explanation", "Current charter income summary"],
    ownerNotes: ["Owner wants privacy until a buyer is verified."],
    brokerOnlyNotes: ["Do not disclose charter underperformance without owner approval."],
    marketSignals: ["Branded open yachts are seeing Monaco interest ahead of summer events."],
    photos: listingPhoto("photo-aqua-63-main", "/segments/broker-yachts.png", "Aqua 63 yacht near Monaco"),
    specSummary: "63ft · 3 cabins · Monaco · commercial VAT",
    imagePrompt: "Elegant grey Riva style yacht near Monaco, realistic luxury brokerage image",
  },
  {
    id: "listing-lagoon-eco-52",
    assetType: "Yacht",
    name: "Lagoon Eco 52",
    builder: "Lagoon",
    model: "52F",
    year: 2020,
    priceEur: 1_250_000,
    lengthFt: 52,
    cabins: 5,
    engines: "Twin Yanmar 80hp",
    engineHours: 1_100,
    location: "Athens, Greece",
    locationLabel: "Athens, Greece",
    locationPrecision: "Area",
    coordinates: { lat: 37.9375, lng: 23.666 },
    vatStatus: "Not Paid",
    availability: "September handover",
    status: "Active",
    ownerId: "seller-vallon",
    exteriorTone: "White catamaran",
    interiorStyle: "Bright charter configuration",
    refitHistory: ["2025 solar array", "2024 sail wardrobe refresh"],
    highlights: ["Five-cabin charter layout", "Solar upgrades", "Strong weekly revenue history"],
    weaknesses: ["VAT not paid", "Higher engine hours"],
    idealBuyer: "Charter-minded buyer seeking a revenue platform rather than a private family yacht.",
    documents: [
      { id: "doc-lagoon-charter", title: "Charter revenue summary", category: "Finance", status: "Approved", updatedAt: "2026-05-09" },
      { id: "doc-lagoon-spec", title: "Equipment list", category: "Specs", status: "Approved", updatedAt: "2026-05-07" },
      { id: "doc-lagoon-survey", title: "Latest survey", category: "Survey", status: "Missing", updatedAt: "2026-05-01" },
    ],
    comps: [
      { name: "Fountaine Pajot 51 2021", priceEur: 1_340_000, note: "Newer with smaller revenue file." },
      { name: "Lagoon 50 2019", priceEur: 1_090_000, note: "Lower ask, more refit needed." },
    ],
    faqs: [
      { question: "Is she private use ready?", answer: "She is better framed as a charter platform unless the buyer accepts VAT and wear trade-offs.", source: "Charter revenue summary" },
    ],
    objections: [],
    missingInfo: ["Updated survey", "VAT import scenario"],
    ownerNotes: ["Seller cares most about clean handover after summer bookings."],
    brokerOnlyNotes: ["Do not promise September handover until charter calendar is checked."],
    marketSignals: ["Income-producing catamarans are still drawing charter-operator buyers."],
    photos: listingPhoto("photo-lagoon-eco-main", "/segments/broker-yachts.png", "Lagoon Eco 52 catamaran in Greece"),
    specSummary: "52ft catamaran · 5 cabins · Athens",
    imagePrompt: "White sailing catamaran at anchor in Greece, premium brokerage style",
  },
  {
    id: "listing-ferrari-sf90-assetto",
    assetType: "Car",
    name: "SF90 Assetto Fiorano",
    builder: "Ferrari",
    model: "SF90 Stradale",
    year: 2023,
    priceEur: 670_000,
    lengthFt: 16,
    cabins: 2,
    engines: "Hybrid V8, 986 hp",
    engineHours: 0,
    location: "Munich, Germany",
    locationLabel: "Munich, Germany",
    locationPrecision: "Area",
    coordinates: { lat: 48.1351, lng: 11.582 },
    vatStatus: "EU VAT Paid",
    availability: "Immediate collection",
    status: "Active",
    ownerId: "seller-nordline",
    exteriorTone: "Rosso Corsa with carbon package",
    interiorStyle: "Black Alcantara with red stitching",
    refitHistory: ["Factory warranty until 2027", "2026 annual service completed"],
    highlights: ["Assetto Fiorano pack", "EU VAT paid", "6,200 km", "Full Ferrari service history"],
    weaknesses: ["Track package limits comfort", "Red spec is bold"],
    idealBuyer: "Collector wanting a VAT-paid EU hypercar with clean provenance.",
    documents: [
      { id: "doc-sf90-title", title: "German title and registration", category: "Title", status: "Approved", updatedAt: "2026-05-14" },
      { id: "doc-sf90-service", title: "Ferrari service file", category: "Maintenance", status: "Approved", updatedAt: "2026-05-16" },
      { id: "doc-sf90-media", title: "Studio media set", category: "Media", status: "Approved", updatedAt: "2026-05-20" },
    ],
    comps: [
      { name: "SF90 Assetto Fiorano 2022", priceEur: 635_000, note: "Higher mileage, non-red spec." },
      { name: "296 GTB Assetto 2024", priceEur: 395_000, note: "Different segment, easier daily use." },
    ],
    faqs: [
      { question: "Is VAT recoverable?", answer: "EU VAT-paid status is documented; buyer tax treatment needs advisor confirmation.", source: "German title and registration" },
    ],
    objections: [],
    missingInfo: ["Paint meter report"],
    ownerNotes: ["Dealer wants proof of funds before disclosing storage location."],
    brokerOnlyNotes: ["Consignor will not entertain trade offers."],
    marketSignals: ["Low-mileage SF90 Assetto cars are stabilizing after Q1 softness."],
    coreFacts: [
      { label: "Make", value: "Ferrari" },
      { label: "Model", value: "SF90 Stradale" },
      { label: "Powertrain", value: "Hybrid V8, 986 hp" },
      { label: "Mileage", value: "6,200 km" },
      { label: "Interior", value: "Black Alcantara with red stitching" },
      { label: "Exterior", value: "Rosso Corsa with carbon package" },
    ],
    photos: listingPhoto("photo-sf90-main", "/segments/broker-cars.png", "Ferrari SF90 in a private showroom"),
    specSummary: "6,200 km · VAT paid · Munich",
    imagePrompt: "Ferrari SF90 in a clean luxury showroom, red paint, realistic automotive listing image",
  },
  {
    id: "listing-porsche-gt3rs-weissach",
    assetType: "Car",
    name: "GT3 RS Weissach",
    builder: "Porsche",
    model: "911 GT3 RS",
    year: 2024,
    priceEur: 385_000,
    lengthFt: 15,
    cabins: 2,
    engines: "4.0L naturally aspirated flat-six",
    engineHours: 0,
    location: "Stuttgart, Germany",
    locationLabel: "Stuttgart, Germany",
    locationPrecision: "Private",
    coordinates: { lat: 48.7758, lng: 9.1829 },
    vatStatus: "EU VAT Paid",
    availability: "Two-week release",
    status: "Pre-Market",
    ownerId: "seller-nordline",
    exteriorTone: "Ice Grey Metallic",
    interiorStyle: "Weissach carbon bucket seats",
    refitHistory: ["Delivery inspection complete"],
    highlights: ["Weissach package", "PTS-adjacent neutral spec", "1,400 km", "European car"],
    weaknesses: ["Pre-market seller approval required", "Track-focused ride"],
    idealBuyer: "Collector wanting a near-new GT allocation without waiting.",
    documents: [
      { id: "doc-gt3rs-spec", title: "Factory option sheet", category: "Specs", status: "Approved", updatedAt: "2026-05-12" },
      { id: "doc-gt3rs-title", title: "Ownership file", category: "Title", status: "Restricted", updatedAt: "2026-05-12" },
      { id: "doc-gt3rs-media", title: "Dealer photo set", category: "Media", status: "Approved", updatedAt: "2026-05-21" },
    ],
    comps: [
      { name: "GT3 RS Weissach 2023", priceEur: 365_000, note: "More mileage, louder color." },
      { name: "911 S/T 2024", priceEur: 525_000, note: "Collector premium, different usage." },
    ],
    faqs: [],
    objections: [],
    missingInfo: ["Seller-approved ownership disclosure"],
    ownerNotes: ["Consignor wants a discreet buyer and no public listing blast."],
    brokerOnlyNotes: ["Seller will release VIN only after verification."],
    marketSignals: ["GT3 RS premiums are narrower, making spec quality matter more."],
    coreFacts: [
      { label: "Make", value: "Porsche" },
      { label: "Model", value: "911 GT3 RS" },
      { label: "Powertrain", value: "4.0L naturally aspirated flat-six" },
      { label: "Mileage", value: "1,400 km" },
      { label: "Interior", value: "Weissach carbon bucket seats" },
      { label: "Exterior", value: "Ice Grey Metallic" },
    ],
    photos: listingPhoto("photo-gt3rs-main", "/segments/broker-cars.png", "Porsche GT3 RS in a private showroom"),
    specSummary: "1,400 km · Weissach · Stuttgart",
    imagePrompt: "Ice grey Porsche 911 GT3 RS in a private showroom, realistic premium car photography",
  },
  {
    id: "listing-range-rover-sv",
    assetType: "Car",
    name: "Range Rover SV Serenity",
    builder: "Range Rover",
    model: "SV LWB",
    year: 2025,
    priceEur: 265_000,
    lengthFt: 17,
    cabins: 4,
    engines: "P615 V8",
    engineHours: 0,
    location: "London, United Kingdom",
    locationLabel: "London, United Kingdom",
    locationPrecision: "Private",
    coordinates: { lat: 51.5072, lng: -0.1276 },
    vatStatus: "EU VAT Paid",
    availability: "Immediate",
    status: "Active",
    ownerId: "seller-nordline",
    exteriorTone: "Eiger Grey over Perlino roof",
    interiorStyle: "Serenity near-aniline leather",
    refitHistory: ["Delivery PDI", "Ceramic coating"],
    highlights: ["Executive rear seating", "Low mileage", "Factory warranty", "Discreet luxury spec"],
    weaknesses: ["Above standard market ask", "UK location adds logistics"],
    idealBuyer: "Principal or family office needing quiet luxury transport immediately.",
    documents: [
      { id: "doc-sv-title", title: "V5 and ownership file", category: "Title", status: "Approved", updatedAt: "2026-05-15" },
      { id: "doc-sv-spec", title: "Factory build sheet", category: "Specs", status: "Approved", updatedAt: "2026-05-15" },
      { id: "doc-sv-media", title: "Approved delivery photos", category: "Media", status: "Approved", updatedAt: "2026-05-19" },
    ],
    comps: [
      { name: "Bentley Bentayga Azure 2025", priceEur: 285_000, note: "More expressive, less discreet." },
      { name: "Mercedes-Maybach GLS 600 2025", priceEur: 245_000, note: "Comparable luxury, different brand read." },
    ],
    faqs: [],
    objections: [],
    missingInfo: [],
    ownerNotes: ["Seller expects same-day response to serious family office requests."],
    brokerOnlyNotes: ["Do not disclose principal name."],
    marketSignals: ["Immediate-delivery luxury SUVs still command a premium in London."],
    coreFacts: [
      { label: "Make", value: "Range Rover" },
      { label: "Model", value: "SV LWB" },
      { label: "Powertrain", value: "P615 V8" },
      { label: "Registration", value: "2025" },
      { label: "Interior", value: "Serenity near-aniline leather" },
      { label: "Exterior", value: "Eiger Grey over Perlino roof" },
    ],
    photos: listingPhoto("photo-range-rover-main", "/segments/broker-cars.png", "Range Rover SV outside a private residence"),
    specSummary: "2025 · executive rear seats · London",
    imagePrompt: "Grey Range Rover SV in front of a modern private residence, premium automotive listing image",
  },
  {
    id: "listing-monaco-penthouse",
    assetType: "Real Estate",
    name: "Port Hercules Penthouse",
    builder: "Monaco",
    model: "Harbor Penthouse",
    year: 2017,
    priceEur: 18_500_000,
    lengthFt: 265,
    cabins: 4,
    engines: "Private elevator, 3 parking spaces",
    engineHours: 0,
    location: "Monaco",
    address: "Port Hercules private address label",
    locationLabel: "Port Hercules, Monaco",
    locationPrecision: "Private",
    coordinates: { lat: 43.7353, lng: 7.4211 },
    vatStatus: "Unknown",
    availability: "Private viewing by approval",
    status: "Pre-Market",
    ownerId: "seller-marceau",
    exteriorTone: "Harbor-facing terrace",
    interiorStyle: "Contemporary stone and walnut",
    refitHistory: ["2025 terrace lighting", "2024 kitchen and AV upgrade"],
    highlights: ["Harbor view", "Private elevator", "Three parking spaces", "Pre-market discretion"],
    weaknesses: ["Ownership structure requires legal review", "Premium ask"],
    idealBuyer: "UHNW buyer wanting a discreet Monaco base with event-week presence.",
    documents: [
      { id: "doc-penthouse-floorplan", title: "Approved floor plan", category: "Specs", status: "Approved", updatedAt: "2026-05-12" },
      { id: "doc-penthouse-media", title: "Broker-approved image set", category: "Media", status: "Approved", updatedAt: "2026-05-18" },
      { id: "doc-penthouse-title", title: "Ownership structure memo", category: "Title", status: "Restricted", updatedAt: "2026-05-19" },
    ],
    comps: [
      { name: "Larvotto sea-view apartment", priceEur: 15_900_000, note: "Less event visibility, renovated." },
      { name: "Fontvieille duplex", priceEur: 12_800_000, note: "More space, weaker harbor view." },
    ],
    faqs: [],
    objections: [],
    missingInfo: ["Legal share-transfer note", "Service charge detail"],
    ownerNotes: ["Owner wants no public portal exposure before proof of funds."],
    brokerOnlyNotes: ["Owner is motivated by a family relocation timeline; keep private."],
    marketSignals: ["Pre-market Monaco inventory is scarce ahead of event season."],
    coreFacts: [
      { label: "Property type", value: "Penthouse apartment" },
      { label: "Area", value: "265 sqm" },
      { label: "Bedrooms", value: "4" },
      { label: "Amenities", value: "Private elevator, 3 parking spaces" },
      { label: "Interior", value: "Contemporary stone and walnut" },
      { label: "Outdoor", value: "Harbor-facing terrace" },
    ],
    photos: listingPhoto("photo-monaco-penthouse-main", "/segments/broker-real-estate.png", "Port Hercules penthouse terrace"),
    specSummary: "265 sqm · 4 beds · harbor view",
    imagePrompt: "Luxury Monaco harbor penthouse terrace with sea view, realistic real estate photography",
  },
  {
    id: "listing-provence-villa",
    assetType: "Real Estate",
    name: "Mas de Lumiere",
    builder: "Provence",
    model: "Stone Estate",
    year: 1890,
    priceEur: 6_800_000,
    lengthFt: 420,
    cabins: 7,
    engines: "Pool, guest house, olive grove",
    engineHours: 0,
    location: "Gordes, France",
    address: "Gordes private estate area",
    locationLabel: "Gordes, France",
    locationPrecision: "Area",
    coordinates: { lat: 43.912, lng: 5.2007 },
    vatStatus: "Unknown",
    availability: "June private viewings",
    status: "Active",
    ownerId: "seller-marceau",
    exteriorTone: "Restored limestone farmhouse",
    interiorStyle: "Warm stone, linen, and natural oak",
    refitHistory: ["2024 guest house renovation", "2023 pool and landscaping"],
    highlights: ["Guest house", "Olive grove", "Turnkey interiors", "Privacy without isolation"],
    weaknesses: ["Seasonal maintenance load", "Longer airport transfer"],
    idealBuyer: "Family buyer seeking a lifestyle estate with guest capacity and privacy.",
    documents: [
      { id: "doc-provence-floorplan", title: "Floor plan and land parcel", category: "Specs", status: "Approved", updatedAt: "2026-05-11" },
      { id: "doc-provence-media", title: "Editorial photo pack", category: "Media", status: "Approved", updatedAt: "2026-05-17" },
      { id: "doc-provence-survey", title: "Building condition note", category: "Survey", status: "Approved", updatedAt: "2026-05-09" },
    ],
    comps: [
      { name: "Luberon restored mas", priceEur: 5_900_000, note: "Less land, older interiors." },
      { name: "Gordes contemporary villa", priceEur: 7_400_000, note: "Newer build, less character." },
    ],
    faqs: [],
    objections: [
      { buyerId: "buyer-mark-liu", label: "Airport access", detail: "Asked whether transfer time is too long for weekend use.", raisedAt: "2026-05-20" },
    ],
    missingInfo: ["Caretaker contract", "Latest utility cost summary"],
    ownerNotes: ["Seller wants serious lifestyle buyers, not pure investment traffic."],
    brokerOnlyNotes: ["Seller is open to furniture inclusion only near ask."],
    marketSignals: ["Turnkey Provence estates are seeing renewed US and Singapore interest."],
    coreFacts: [
      { label: "Property type", value: "Stone estate" },
      { label: "Area", value: "420 sqm" },
      { label: "Bedrooms", value: "7" },
      { label: "Amenities", value: "Pool, guest house, olive grove" },
      { label: "Interior", value: "Warm stone, linen, and natural oak" },
      { label: "Outdoor", value: "Restored limestone farmhouse" },
    ],
    photos: listingPhoto("photo-provence-villa-main", "/segments/broker-real-estate.png", "Provence stone estate with pool"),
    specSummary: "420 sqm · 7 beds · guest house",
    imagePrompt: "Restored Provence stone estate with pool and olive trees, golden hour real estate photography",
  },
  {
    id: "listing-dubai-sky-villa",
    assetType: "Real Estate",
    name: "Palm Sky Villa",
    builder: "Dubai",
    model: "Sky Villa",
    year: 2022,
    priceEur: 9_900_000,
    lengthFt: 510,
    cabins: 5,
    engines: "Private pool, beach club access",
    engineHours: 0,
    location: "Palm Jumeirah, Dubai",
    address: "Palm Jumeirah private tower label",
    locationLabel: "Palm Jumeirah, Dubai",
    locationPrecision: "Private",
    coordinates: { lat: 25.1124, lng: 55.139 },
    vatStatus: "Commercial",
    availability: "Immediate private tour",
    status: "Active",
    ownerId: "seller-marceau",
    exteriorTone: "Full-height Gulf views",
    interiorStyle: "Contemporary marble and bronze",
    refitHistory: ["2025 smart-home upgrade", "2024 custom closets"],
    highlights: ["Private pool", "Beach club access", "High-floor views", "Immediate availability"],
    weaknesses: ["Service fees need explanation", "High-gloss interiors"],
    idealBuyer: "Relocation or investment buyer who wants a serviced trophy residence now.",
    documents: [
      { id: "doc-dubai-floorplan", title: "Floor plan", category: "Specs", status: "Approved", updatedAt: "2026-05-13" },
      { id: "doc-dubai-service", title: "Service fee summary", category: "Finance", status: "Restricted", updatedAt: "2026-05-18" },
      { id: "doc-dubai-media", title: "Approved video stills", category: "Media", status: "Approved", updatedAt: "2026-05-21" },
    ],
    comps: [
      { name: "Bluewaters penthouse", priceEur: 8_700_000, note: "Lower ask, less private outdoor area." },
      { name: "Palm branded residence", priceEur: 11_200_000, note: "More amenities, less immediate availability." },
    ],
    faqs: [],
    objections: [],
    missingInfo: ["Net-yield scenario", "Service fee approval for buyer room"],
    ownerNotes: ["Owner wants international buyer qualification before video tour."],
    brokerOnlyNotes: ["Owner is testing price before possible public launch."],
    marketSignals: ["Branded residences on Palm continue to attract relocation capital."],
    coreFacts: [
      { label: "Property type", value: "Sky villa" },
      { label: "Area", value: "510 sqm" },
      { label: "Bedrooms", value: "5" },
      { label: "Amenities", value: "Private pool, beach club access" },
      { label: "Interior", value: "Contemporary marble and bronze" },
      { label: "Outdoor", value: "Full-height Gulf views" },
    ],
    photos: listingPhoto("photo-dubai-sky-villa-main", "/segments/broker-real-estate.png", "Dubai Palm sky villa with sea view"),
    specSummary: "510 sqm · 5 beds · private pool",
    imagePrompt: "Dubai Palm Jumeirah sky villa interior with sea view and private pool, realistic real estate photo",
  },
];

export const buyers: BuyerProfile[] = [
  {
    id: "buyer-helena-rossi",
    assetTypes: ["Yacht"],
    name: "Helena Rossi",
    company: "Rossi Family Office",
    country: "Italy",
    budgetMinEur: 1_200_000,
    budgetMaxEur: 3_800_000,
    sizeRangeFt: [52, 75],
    preferredBrands: ["Princess", "Ferretti", "Riva"],
    preferredLocations: ["Mallorca", "Monaco", "France"],
    lifestylePreferences: ["Light interior", "Family use", "Turnkey Mediterranean access"],
    mustHaves: ["EU VAT paid", "3 cabins", "Approved documents"],
    dealBreakers: ["Heavy refit", "Unclear VAT"],
    objections: ["Does not want dark glossy interiors."],
    rejectedAssets: [{ listingId: "listing-riva-aqua-63", reason: "Commercial VAT context felt too complex for family use.", rejectedAt: "2026-05-19" }],
    urgency: "This Season",
    decisionTimeline: "Wants a shortlist and first viewing windows before the second week of June.",
    communicationStyle: "Concise WhatsApp first, detailed email after the shortlist.",
    relationshipNotes: ["Spouse cares about natural light and easy guest circulation."],
    currentStage: "Shortlist Sent",
    lastContactedAt: "2026-05-22",
    nextActionDueAt: "2026-05-24",
    verificationCaseId: "verif-helena-aurora",
    tags: ["family office", "VAT-sensitive", "summer timing", "Med"],
  },
  {
    id: "buyer-daniel-brenner",
    assetTypes: ["Yacht"],
    name: "Daniel Brenner",
    company: "Brenner Holdings",
    country: "Germany",
    budgetMinEur: 1_000_000,
    budgetMaxEur: 1_550_000,
    sizeRangeFt: [50, 60],
    preferredBrands: ["Princess", "Ferretti", "Azimut"],
    preferredLocations: ["Mallorca", "France"],
    lifestylePreferences: ["Light interior", "Low hours", "Family use"],
    mustHaves: ["EU VAT paid", "3 cabins"],
    dealBreakers: ["High engine hours", "Major refit"],
    objections: ["Worries about stabilizers on sub-60ft yachts."],
    rejectedAssets: [],
    urgency: "Immediate",
    decisionTimeline: "Needs a clean comparison by tomorrow to decide on weekend travel.",
    communicationStyle: "Short WhatsApp updates; send full documents only after he replies.",
    relationshipNotes: ["Asked twice not to repeat options with dark interiors."],
    currentStage: "Qualified",
    lastContactedAt: "2026-05-23",
    nextActionDueAt: "2026-05-24",
    verificationCaseId: "verif-daniel-palmera",
    tags: ["fast buyer", "family", "VAT-paid", "Mallorca"],
  },
  {
    id: "buyer-sofia-klein",
    assetTypes: ["Car"],
    name: "Sofia Klein",
    company: "Klein Collection",
    country: "Switzerland",
    budgetMinEur: 300_000,
    budgetMaxEur: 750_000,
    sizeRangeFt: [14, 18],
    preferredBrands: ["Ferrari", "Porsche"],
    preferredLocations: ["Germany", "Switzerland", "Italy"],
    lifestylePreferences: ["Low mileage", "Collector provenance", "Neutral or iconic spec"],
    mustHaves: ["EU VAT paid", "Approved documents"],
    dealBreakers: ["Accident history", "Missing service file"],
    objections: ["Does not want a car that has been heavily tracked."],
    rejectedAssets: [],
    urgency: "This Quarter",
    decisionTimeline: "Ready to move within 30 days for the right provenance file.",
    communicationStyle: "Prefers email with numbered facts and then a short call.",
    relationshipNotes: ["Responds well to provenance-first framing over hype."],
    currentStage: "Viewing Planned",
    lastContactedAt: "2026-05-21",
    nextActionDueAt: "2026-05-25",
    verificationCaseId: "verif-sofia-sf90",
    tags: ["collector", "cars", "provenance", "VAT-paid"],
  },
  {
    id: "buyer-mark-liu",
    assetTypes: ["Real Estate"],
    name: "Mark Liu",
    company: "Liu Capital",
    country: "Singapore",
    budgetMinEur: 5_000_000,
    budgetMaxEur: 10_000_000,
    sizeRangeFt: [300, 540],
    preferredBrands: ["Provence", "Dubai"],
    preferredLocations: ["France", "Dubai", "Monaco"],
    lifestylePreferences: ["Privacy", "Guest capacity", "Turnkey interiors"],
    mustHaves: ["Approved documents", "Private viewing"],
    dealBreakers: ["Heavy renovation", "Weak airport access"],
    objections: ["Questions weekend usability if airport transfer is long."],
    rejectedAssets: [],
    urgency: "This Season",
    decisionTimeline: "Wants two private viewings in June, one European and one Dubai option.",
    communicationStyle: "Detailed email briefing for his assistant; broker call for trade-offs.",
    relationshipNotes: ["Family wants warm materials, not ultra-gloss interiors."],
    currentStage: "Shortlist Sent",
    lastContactedAt: "2026-05-20",
    nextActionDueAt: "2026-05-24",
    verificationCaseId: "verif-mark-provence",
    tags: ["real estate", "privacy", "family", "international"],
  },
  {
    id: "buyer-amira-haddad",
    assetTypes: ["Yacht"],
    name: "Amira Haddad",
    company: "Haddad Advisory",
    country: "United Arab Emirates",
    budgetMinEur: 1_500_000,
    budgetMaxEur: 4_500_000,
    sizeRangeFt: [60, 78],
    preferredBrands: ["Riva", "Princess", "Sunseeker"],
    preferredLocations: ["Monaco", "Mallorca", "Italy"],
    lifestylePreferences: ["Brand presence", "Outdoor entertaining", "Fast access"],
    mustHaves: ["Approved documents", "3 cabins"],
    dealBreakers: ["Weak crew setup", "Unclear seller identity"],
    objections: ["Wants crew comfort explained before family trips."],
    rejectedAssets: [{ listingId: "listing-lagoon-eco-52", reason: "Charter catamaran did not match private-use preference.", rejectedAt: "2026-05-17" }],
    urgency: "Exploratory",
    decisionTimeline: "Exploring for late summer, will accelerate if a pre-market Riva is credible.",
    communicationStyle: "Broker should call first before sending long documents.",
    relationshipNotes: ["Highly sensitive to privacy and seller identity."],
    currentStage: "New Inquiry",
    lastContactedAt: "2026-05-19",
    nextActionDueAt: "2026-05-27",
    verificationCaseId: "verif-amira-aqua",
    tags: ["privacy", "yacht", "brand-led", "needs review"],
  },
  {
    id: "buyer-priya-shah",
    assetTypes: ["Car", "Real Estate"],
    name: "Priya Shah",
    company: "Shah Ventures",
    country: "United Kingdom",
    budgetMinEur: 200_000,
    budgetMaxEur: 11_000_000,
    sizeRangeFt: [15, 520],
    preferredBrands: ["Range Rover", "Dubai", "Porsche"],
    preferredLocations: ["London", "Dubai", "Germany"],
    lifestylePreferences: ["Immediate availability", "Discreet luxury", "Principal-ready"],
    mustHaves: ["Approved documents", "Immediate access"],
    dealBreakers: ["Publicly exposed seller", "Long lead time"],
    objections: ["Needs to know what can be shared with her principal safely."],
    rejectedAssets: [],
    urgency: "Immediate",
    decisionTimeline: "Principal can decide this week if the broker pack is clean.",
    communicationStyle: "Assistant receives written pack; principal gets a short summary.",
    relationshipNotes: ["Buyer-safe wording matters; avoid internal risk labels."],
    currentStage: "Negotiation",
    lastContactedAt: "2026-05-23",
    nextActionDueAt: "2026-05-24",
    verificationCaseId: "verif-priya-range-rover",
    tags: ["principal", "cars", "real estate", "discreet"],
  },
];

export const sellers: SellerProfile[] = [
  {
    id: "seller-vallon",
    name: "Vallon Marine Holdings",
    assetIds: ["listing-aurora-72", "listing-palmera-55", "listing-riva-aqua-63", "listing-lagoon-eco-52"],
    motivation: "Rotating family marine assets before summer operating costs peak.",
    communicationExpectation: "Weekly concise update with lead quality, objections, and next actions.",
    pricingSensitivity: "Will defend asking price unless speed and certainty are obvious.",
    feedbackHistory: ["Asked for fewer unqualified brochure requests.", "Wants objections summarized without buyer gossip."],
    reportingCadence: "Weekly Friday owner update",
    nextOwnerUpdateDueAt: "2026-05-24",
  },
  {
    id: "seller-nordline",
    name: "Nordline Collector Cars",
    assetIds: ["listing-ferrari-sf90-assetto", "listing-porsche-gt3rs-weissach", "listing-range-rover-sv"],
    motivation: "Freeing floorplan exposure while keeping rare allocations discreet.",
    communicationExpectation: "Daily response on serious verified collector leads.",
    pricingSensitivity: "Open to clean all-cash closings; no trade discussions.",
    feedbackHistory: ["Requested proof-of-funds before VIN disclosure.", "Wants provenance questions answered from service files only."],
    reportingCadence: "Twice weekly collector update",
    nextOwnerUpdateDueAt: "2026-05-26",
  },
  {
    id: "seller-marceau",
    name: "Marceau Private Estates",
    assetIds: ["listing-monaco-penthouse", "listing-provence-villa", "listing-dubai-sky-villa"],
    motivation: "Testing private market demand before public launch decisions.",
    communicationExpectation: "Owner update must separate curiosity from qualified private viewings.",
    pricingSensitivity: "Sensitive to public price reductions; prefers controlled negotiation.",
    feedbackHistory: ["Asked for privacy-safe buyer summaries.", "Wants service fee objections tracked."],
    reportingCadence: "Weekly private-market report",
    nextOwnerUpdateDueAt: "2026-05-25",
  },
];

export const conversations: Conversation[] = [
  { id: "conv-helena-1", buyerId: "buyer-helena-rossi", listingId: "listing-aurora-72", channel: "Call", summary: "Helena liked Aurora 72's light interior and wants owner-safe pricing context before viewings.", sentiment: "Positive", occurredAt: "2026-05-22T11:20:00+03:00", needsSummary: false },
  { id: "conv-daniel-1", buyerId: "buyer-daniel-brenner", listingId: "listing-palmera-55", channel: "WhatsApp", summary: "Daniel asked for a Princess F55 versus Ferretti comparison and viewing windows by tomorrow.", sentiment: "Positive", occurredAt: "2026-05-23T17:05:00+03:00", needsSummary: true },
  { id: "conv-sofia-1", buyerId: "buyer-sofia-klein", listingId: "listing-ferrari-sf90-assetto", channel: "Email", summary: "Sofia requested paint meter report and confirmation that SF90 has no track-event history.", sentiment: "Neutral", occurredAt: "2026-05-21T09:45:00+03:00", needsSummary: false },
  { id: "conv-mark-1", buyerId: "buyer-mark-liu", listingId: "listing-provence-villa", channel: "Viewing", summary: "Assistant asked for June viewing path and caretaker contract on Mas de Lumiere.", sentiment: "Positive", occurredAt: "2026-05-20T15:10:00+03:00", needsSummary: false },
  { id: "conv-vallon-1", sellerId: "seller-vallon", listingId: "listing-palmera-55", channel: "Call", summary: "Owner requested weekly report focused on qualified family buyers and document blockers.", sentiment: "Concerned", occurredAt: "2026-05-22T10:00:00+03:00", needsSummary: true },
  { id: "conv-marceau-1", sellerId: "seller-marceau", listingId: "listing-monaco-penthouse", channel: "Email", summary: "Owner approved floor plan sharing after proof-of-funds, but title memo remains restricted.", sentiment: "Neutral", occurredAt: "2026-05-19T13:30:00+03:00", needsSummary: false },
];

export const brokerTasks: BrokerTask[] = [
  { id: "task-daniel-shortlist", title: "Send Daniel's F55 comparison", kind: "Matching", priority: "High", status: "Open", dueAt: "2026-05-24", reason: "He asked for a Princess/Ferretti comparison and viewing windows by tomorrow.", actionLabel: "Open matcher", buyerId: "buyer-daniel-brenner", listingId: "listing-palmera-55" },
  { id: "task-vallon-report", title: "Approve Vallon owner update", kind: "Owner Update", priority: "High", status: "In Progress", dueAt: "2026-05-24", reason: "Owner expects weekly lead quality, objections, and blocker summary today.", actionLabel: "Open report", sellerId: "seller-vallon", listingId: "listing-palmera-55" },
  { id: "task-sofia-paint", title: "Request SF90 paint meter report", kind: "Document", priority: "Medium", status: "Waiting", dueAt: "2026-05-25", reason: "Sofia will not proceed without provenance and paint confirmation.", actionLabel: "Request doc", buyerId: "buyer-sofia-klein", sellerId: "seller-nordline", listingId: "listing-ferrari-sf90-assetto" },
  { id: "task-amira-review", title: "Review Amira access before Riva documents", kind: "Verification", priority: "Critical", status: "Open", dueAt: "2026-05-24", reason: "Privacy-sensitive pre-market Riva request has review signals.", actionLabel: "Open case", buyerId: "buyer-amira-haddad", listingId: "listing-riva-aqua-63" },
  { id: "task-mark-viewing", title: "Confirm Provence caretaker contract", kind: "Viewing", priority: "Medium", status: "Open", dueAt: "2026-05-25", reason: "Mark's assistant asked for caretaker details before booking June viewing.", actionLabel: "Open owner", buyerId: "buyer-mark-liu", sellerId: "seller-marceau", listingId: "listing-provence-villa" },
  { id: "task-priya-pack", title: "Prepare principal-safe Range Rover pack", kind: "Follow-Up", priority: "High", status: "Open", dueAt: "2026-05-24", reason: "Priya needs a buyer-safe summary for principal approval this week.", actionLabel: "Open buyer", buyerId: "buyer-priya-shah", listingId: "listing-range-rover-sv" },
];

export const verificationCases: VerificationCase[] = [
  {
    id: "verif-helena-aurora",
    buyerId: "buyer-helena-rossi",
    listingId: "listing-aurora-72",
    requestedAccess: "Approved document pack and Palma viewing",
    status: "Verified",
    score: 92,
    recommendedAction: "Proceed with broker-approved access.",
    signals: [
      { label: "Identity", state: "Pass", detail: "Passport copy and relationship context recorded." },
      { label: "Company", state: "Pass", detail: "Rossi Family Office is recorded against the buyer profile." },
      { label: "Proof-of-funds readiness", state: "Pass", detail: "Bank reference readiness recorded by broker." },
      { label: "AML-style signals", state: "Pass", detail: "No prototype sanctions, PEP, watchlist, or adverse-media flags." },
    ],
    updatedAt: "2026-05-22T12:00:00+03:00",
  },
  {
    id: "verif-daniel-palmera",
    buyerId: "buyer-daniel-brenner",
    listingId: "listing-palmera-55",
    requestedAccess: "Title extract and viewing booking",
    status: "Needs Review",
    score: 64,
    recommendedAction: "Request buying-entity confirmation before restricted title material.",
    signals: [
      { label: "Identity", state: "Pass", detail: "Buyer identity details are present." },
      { label: "Company", state: "Review", detail: "Buying entity not yet confirmed." },
      { label: "Proof-of-funds readiness", state: "Review", detail: "Readiness evidence requested but not received." },
    ],
    updatedAt: "2026-05-23T16:00:00+03:00",
  },
  {
    id: "verif-amira-aqua",
    buyerId: "buyer-amira-haddad",
    listingId: "listing-riva-aqua-63",
    requestedAccess: "Pre-market seller identity and VAT memo",
    status: "High Risk",
    score: 34,
    recommendedAction: "Hold access and escalate with an audit trail.",
    signals: [
      { label: "Identity", state: "Review", detail: "Identity file is not current enough for seller-sensitive disclosure." },
      { label: "Contact consistency", state: "Review", detail: "Assistant and principal contact routes need confirmation." },
      { label: "AML-style signals", state: "Fail", detail: "Prototype adverse-media review flag requires broker escalation." },
    ],
    updatedAt: "2026-05-20T10:30:00+03:00",
  },
  {
    id: "verif-priya-range-rover",
    buyerId: "buyer-priya-shah",
    listingId: "listing-range-rover-sv",
    requestedAccess: "Principal-safe vehicle pack",
    status: "Verified",
    score: 88,
    recommendedAction: "Proceed with broker-approved pack; keep principal identity private.",
    signals: [
      { label: "Identity", state: "Pass", detail: "Assistant and principal access path verified." },
      { label: "Company", state: "Pass", detail: "Shah Ventures context recorded." },
      { label: "Proof-of-funds readiness", state: "Pass", detail: "Broker recorded readiness signal." },
    ],
    updatedAt: "2026-05-23T14:20:00+03:00",
  },
];

export const matchResults: MatchResult[] = [
  { id: "match-helena-aurora", buyerId: "buyer-helena-rossi", listingId: "listing-aurora-72", category: "Exact Match", fitScore: 94, rationale: "Aurora 72 matches Helena's VAT, family layout, light interior, and summer timing.", criteriaMet: ["Inside budget", "Size range", "Preferred brand", "EU VAT paid"], missingCriteria: ["Owner-approved drone video"], talkingPoints: ["Light modern interior", "Stabilizers", "Turnkey Med berth"] },
  { id: "match-daniel-palmera", buyerId: "buyer-daniel-brenner", listingId: "listing-palmera-55", category: "Exact Match", fitScore: 91, rationale: "Palmera F55 fits Daniel's budget, size, VAT, and light interior brief.", criteriaMet: ["Inside budget", "Size range", "Preferred brand", "EU VAT paid"], missingCriteria: ["Tender invoice"], talkingPoints: ["Low engine hours", "Strong family layout"] },
  { id: "match-sofia-sf90", buyerId: "buyer-sofia-klein", listingId: "listing-ferrari-sf90-assetto", category: "Close Match", fitScore: 86, rationale: "SF90 delivers provenance, VAT-paid status, and iconic collector appeal within cap.", criteriaMet: ["Inside budget", "Preferred brand", "EU VAT paid"], missingCriteria: ["Paint meter report"], talkingPoints: ["Assetto Fiorano pack", "Full Ferrari service history"] },
  { id: "match-mark-provence", buyerId: "buyer-mark-liu", listingId: "listing-provence-villa", category: "Close Match", fitScore: 84, rationale: "Mas de Lumiere fits privacy, guest capacity, turnkey interiors, and budget.", criteriaMet: ["Inside budget", "Size range", "Taste signal"], missingCriteria: ["Caretaker contract"], talkingPoints: ["Guest house", "Olive grove"] },
  { id: "match-priya-range", buyerId: "buyer-priya-shah", listingId: "listing-range-rover-sv", category: "Exact Match", fitScore: 90, rationale: "Range Rover SV is immediate, discreet, principal-ready, and document complete.", criteriaMet: ["Inside budget", "Size range", "Approved documents"], missingCriteria: [], talkingPoints: ["Executive rear seating", "Discreet luxury spec"] },
];

export const followUpDrafts: FollowUpDraft[] = [
  { id: "draft-daniel-palmera", buyerId: "buyer-daniel-brenner", listingId: "listing-palmera-55", kind: "Post-Call Follow-Up", channel: "WhatsApp", status: "Edited", subject: "F55 comparison", body: "Daniel, I have Palmera F55 as the strongest fit and will send the Ferretti comparison with stabilizer trade-offs and viewing windows today.", createdAt: "2026-05-23T17:20:00+03:00" },
  { id: "draft-helena-aurora", buyerId: "buyer-helena-rossi", listingId: "listing-aurora-72", kind: "Inquiry Reply", channel: "Email", status: "Approved", subject: "Aurora 72 shortlist note", body: "Helena, Aurora 72 remains the cleanest match for light interior, VAT-paid status, and Palma viewing timing. I kept seller-sensitive details out of this note.", createdAt: "2026-05-22T12:35:00+03:00" },
  { id: "draft-sofia-sf90", buyerId: "buyer-sofia-klein", listingId: "listing-ferrari-sf90-assetto", kind: "Viewing Recap", channel: "Email", status: "Draft", subject: "SF90 provenance recap", body: "Sofia, I will confirm paint meter and track-event history before recommending next steps.", createdAt: "2026-05-21T10:15:00+03:00" },
];

export const sellerReportInputs: SellerReportInput[] = [
  { id: "report-vallon-week21", sellerId: "seller-vallon", listingId: "listing-palmera-55", period: "Week ending May 24", inquiries: 18, qualifiedLeads: 5, viewings: 2, commonObjections: ["Stabilizers questioned", "Tender invoice missing", "Buyers want clear VAT proof"], marketMovement: ["VAT-paid 55ft family yachts remain scarce", "Two competing flybridges went under offer"], nextWeekPlan: ["Clear oil analysis", "Send Daniel comparison", "Push Helena Aurora alternative"], history: [{ period: "Week ending May 3", inquiries: 9, qualifiedLeads: 2, viewings: 1 }, { period: "Week ending May 10", inquiries: 12, qualifiedLeads: 3, viewings: 1 }, { period: "Week ending May 17", inquiries: 14, qualifiedLeads: 4, viewings: 2 }] },
  { id: "report-nordline-week21", sellerId: "seller-nordline", listingId: "listing-ferrari-sf90-assetto", period: "Week ending May 24", inquiries: 11, qualifiedLeads: 4, viewings: 1, commonObjections: ["Paint meter report needed", "Track usage questions", "Asking price compared with 2022 cars"], marketMovement: ["SF90 Assetto supply is stabilizing", "Collectors still pay for clean Ferrari service files"], nextWeekPlan: ["Add paint meter report", "Verify Sofia's viewing slot", "Prepare provenance-first pack"], history: [{ period: "Week ending May 3", inquiries: 16, qualifiedLeads: 5, viewings: 2 }, { period: "Week ending May 10", inquiries: 13, qualifiedLeads: 4, viewings: 2 }, { period: "Week ending May 17", inquiries: 12, qualifiedLeads: 4, viewings: 1 }] },
  { id: "report-marceau-week21", sellerId: "seller-marceau", listingId: "listing-provence-villa", period: "Week ending May 24", inquiries: 9, qualifiedLeads: 3, viewings: 1, commonObjections: ["Airport transfer time", "Caretaker contract", "Seasonal running costs"], marketMovement: ["US and Singapore families are active on turnkey Provence estates", "Dubai trophy residences still pull relocation capital"], nextWeekPlan: ["Confirm caretaker contract", "Package June viewing windows", "Keep Monaco title memo restricted"], history: [{ period: "Week ending May 3", inquiries: 5, qualifiedLeads: 1, viewings: 0 }, { period: "Week ending May 10", inquiries: 6, qualifiedLeads: 2, viewings: 0 }, { period: "Week ending May 17", inquiries: 8, qualifiedLeads: 2, viewings: 1 }] },
];

export const dealRooms: DealRoom[] = [
  {
    id: "room-helena-design-set",
    buyerId: "buyer-helena-rossi",
    title: "Helena Rossi Private Shortlist",
    status: "Active",
    verificationStatus: "Verified",
    brokerApprovalStatus: "Approved",
    listingIds: ["listing-aurora-72", "listing-palmera-55", "listing-riva-aqua-63"],
    itinerary: ["Review Aurora 72 and Palmera F55 comparison", "Confirm Palma viewing windows", "Share approved survey and VAT documents", "Discuss Riva only if commercial VAT is acceptable"],
    approvedDocumentIds: ["doc-aurora-survey", "doc-aurora-vat", "doc-aurora-service", "doc-palmera-survey", "doc-palmera-vat", "doc-palmera-media", "doc-aqua-spec", "doc-aqua-media"],
    lastUpdatedAt: "2026-05-23T18:15:00+03:00",
  },
  {
    id: "room-priya-principal-pack",
    buyerId: "buyer-priya-shah",
    title: "Priya Shah Principal Pack",
    status: "Active",
    verificationStatus: "Verified",
    brokerApprovalStatus: "Approved",
    listingIds: ["listing-range-rover-sv", "listing-dubai-sky-villa"],
    itinerary: ["Send principal-safe summary", "Confirm London collection or Dubai private tour", "Hold seller identities until broker approval"],
    approvedDocumentIds: ["doc-sv-title", "doc-sv-spec", "doc-sv-media", "doc-dubai-floorplan", "doc-dubai-media"],
    lastUpdatedAt: "2026-05-23T15:30:00+03:00",
  },
  {
    id: "room-mark-estate-tour",
    buyerId: "buyer-mark-liu",
    title: "Mark Liu Estate Tour",
    status: "Draft",
    verificationStatus: "Needs Review",
    brokerApprovalStatus: "Pending",
    listingIds: ["listing-provence-villa", "listing-dubai-sky-villa"],
    itinerary: ["Request final buying-entity details", "Hold restricted service-fee and caretaker notes", "Prepare June viewing route"],
    approvedDocumentIds: ["doc-provence-floorplan", "doc-provence-media", "doc-provence-survey", "doc-dubai-floorplan", "doc-dubai-media"],
    lastUpdatedAt: "2026-05-22T16:10:00+03:00",
  },
];

export const auditEvents: AuditEvent[] = [
  { id: "audit-helena-room-approved", actor: "Broker", label: "Deal room approved", detail: "Helena Rossi Private Shortlist approved with buyer-safe document set only.", occurredAt: "2026-05-23T18:15:00+03:00" },
  { id: "audit-daniel-draft-edited", actor: "Broker", label: "Draft edited", detail: "Broker tightened Daniel follow-up to address stabilizer objection directly.", occurredAt: "2026-05-23T17:25:00+03:00" },
  { id: "audit-vallon-report-generated", actor: "System", label: "Owner report generated", detail: "Palmera F55 owner update prepared for Vallon Marine Holdings.", occurredAt: "2026-05-24T09:00:00+03:00" },
  { id: "audit-amira-access-held", actor: "Broker", label: "Access held", detail: "verif-amira-aqua held before pre-market seller identity and VAT memo sharing.", occurredAt: "2026-05-20T11:00:00+03:00" },
];

/* ---------------------------------------------------------------------------
   Demo clock. The seed data above is authored against a fixed anchor day
   (2026-05-24 = "today" at authoring time). At module load we shift every
   date in the demo objects by whole days so the anchor lands on the real
   today — overdue stays overdue, "due tomorrow" stays tomorrow, and the
   demo pipeline never goes stale. Times of day and timezone offsets are
   preserved; only the date part moves. */
const DEMO_ANCHOR_UTC = Date.UTC(2026, 4, 24);
const TODAY_UTC = (() => {
  const now = new Date();
  return Date.UTC(now.getFullYear(), now.getMonth(), now.getDate());
})();
const DAY_SHIFT = Math.round((TODAY_UTC - DEMO_ANCHOR_UTC) / 86_400_000);

const DATE_STRING_RE = /^(\d{4})-(\d{2})-(\d{2})(.*)$/;

function shiftDateString(value: string): string {
  const match = DATE_STRING_RE.exec(value);
  if (!match) return value;
  const base = new Date(Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3])));
  base.setUTCDate(base.getUTCDate() + DAY_SHIFT);
  const year = base.getUTCFullYear();
  const month = String(base.getUTCMonth() + 1).padStart(2, "0");
  const day = String(base.getUTCDate()).padStart(2, "0");
  return `${year}-${month}-${day}${match[4]}`;
}

function shiftDates(value: unknown): unknown {
  if (typeof value === "string") return shiftDateString(value);
  if (Array.isArray(value)) {
    for (let index = 0; index < value.length; index += 1) value[index] = shiftDates(value[index]);
    return value;
  }
  if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;
    for (const key of Object.keys(record)) record[key] = shiftDates(record[key]);
    return value;
  }
  return value;
}

if (DAY_SHIFT !== 0) {
  for (const collection of [
    yachtListings,
    buyers,
    sellers,
    conversations,
    brokerTasks,
    verificationCases,
    matchResults,
    followUpDrafts,
    sellerReportInputs,
    dealRooms,
    auditEvents,
  ]) {
    shiftDates(collection);
  }
}
