/* Maps a boats.com / YachtWorld-style "Full Details" PDF export (the kind
   generated by their Chrome print/share flow) into the fields our yacht
   listing intake uses, plus extraction of the embedded photos.

   The text mapping (mapYachtPdfText) is pure and runtime-agnostic so it can
   be unit-tested. JPEG extraction (extractPdfJpegs) reads the raw PDF bytes
   and is Node-only. The actual PDF→text step (unpdf) lives in the API route
   so this module stays free of heavy deps for testing. */

/* Field ids intentionally match the yacht intake config so the parsed values
   prefill the review form directly. */
export interface ParsedYachtFields {
  builder: string;
  model: string;
  year: string;
  lengthFt: string;
  cabins: string;
  engines: string;
  propulsion: string;
  condition: string;
  engineHours: string;
  vatStatus: string;
  priceEur: string;
  location: string;
  description: string;
  /* Specs + equipment we captured but that don't map to a single basic
     field — kept together so nothing is lost and the broker can edit it. */
  equipment: string;
}

export interface ParsedYachtPdf {
  fields: ParsedYachtFields;
  /* Notes about low-confidence or conflicting reads, surfaced in the UI. */
  warnings: string[];
}

const PROPULSION_OPTIONS = ["Motor", "Twin diesel", "Diesel", "Hybrid", "Electric", "Sail"];
const CONDITION_OPTIONS = ["New", "Used", "Refit", "Project / needs work"];

/* ---- Text mapping ------------------------------------------------------ */

export function mapYachtPdfText(raw: string): ParsedYachtPdf {
  const text = normalizeWhitespace(raw);
  const warnings: string[] = [];

  // Parse the labelled "Boat Details" block into a generic label→value map.
  // This survives field reordering and unknown extra fields across export
  // variants — far more robust than per-field regexes.
  const details = parseDetailBlock(text);
  const detail = (...labels: string[]): string => {
    for (const label of labels) {
      const value = details[label.toLowerCase()];
      if (value) return value;
    }
    return "";
  };

  const make = detail("Make", "Manufacturer", "Builder") || titleMakeFallback(text);
  const model = detail("Model");
  const year =
    firstMatch(detail("Year"), /\b(19|20)\d{2}\b/) ||
    matchValue(text, /Year:\s*(\d{4})/i) ||
    matchValue(text, /\b(?:19|20)\d{2}\b/);
  const condition = normalizeCondition(detail("Condition"));

  const lengthMeters =
    metersFromText(detail("Length", "LOA", "Length overall")) ??
    parseMeters(text, /(?:Length|LOA):\s*([\d.,]+)\s*m(?:\s*([\d.,]+)\s*cm)?/i);
  const lengthFt = lengthMeters ? String(Math.round(lengthMeters * 3.28084)) : "";

  const priceEur = parsePriceEur(detail("Price", "Asking Price", "Ask"), text, warnings);
  const location = detail("Boat Location", "Located in", "Location") || parseLocation(text);

  const { engines, engineCount } = parseEngines(text);
  const fuelType = detail("Fuel Type", "Fuel").toLowerCase();
  const propulsion = normalizePropulsion(fuelType, engineCount);

  const cabins = firstMatch(detail("Guest Cabins", "Cabins", "Berths"), /\d+/) || parseCabins(text);
  const vatStatus = normalizeVat(detail("Tax", "VAT", "VAT Status"), text, warnings);

  const description = parseDescription(text);
  const equipment = parseEquipment(text);
  const engineHours =
    firstMatch(detail("Engine Hours", "Engine hrs", "Hours"), /[\d,]+/).replace(/,/g, "") ||
    parseEngineHours(description);

  if (!make && !model) {
    warnings.push("Couldn't read the builder/model reliably — please confirm.");
  }
  if (!priceEur) {
    warnings.push("No price detected — add it before saving.");
  }

  return {
    fields: {
      builder: make,
      model,
      year,
      lengthFt,
      cabins,
      engines,
      propulsion,
      condition,
      engineHours,
      vatStatus,
      priceEur,
      location,
      description,
      equipment,
    },
    warnings,
  };
}

/* Known labels in the export's "Boat Details" block. Anchoring on this
   vocabulary (rather than generic "Word:" detection) avoids mis-splitting
   multi-word values like "V Drive" or "Stern Drive". */
const DETAIL_LABELS = [
  "Boat Location",
  "Hull Material",
  "Drive Type",
  "Guest Cabins",
  "Guest Heads",
  "Engine Hours",
  "Cruising Speed",
  "Asking Price",
  "VAT Status",
  "Located in",
  "Fuel Type",
  "Max Speed",
  "Max Draft",
  "Hull Shape",
  "Manufacturer",
  "Length overall",
  "Make",
  "Model",
  "Year",
  "Length",
  "Beam",
  "Price",
  "Condition",
  "Class",
  "Name",
  "Cabins",
  "Heads",
  "Berths",
  "Tax",
  "VAT",
  "Builder",
  "Location",
  "Hours",
  "Ask",
  "Fuel",
];

/* Parse the "Boat Details" section into a lowercased label→value map.
   Each value runs from its own colon to the next known label. */
function parseDetailBlock(text: string): Record<string, string> {
  const start = text.search(/Boat Details/i);
  const end = text.search(/\bDescription\b/i);
  const region =
    start !== -1
      ? text.slice(start + "Boat Details".length, end > start ? end : undefined)
      : text;

  const labelAlternation = [...DETAIL_LABELS]
    .sort((a, b) => b.length - a.length)
    .map(escapeRegExp)
    .join("|");
  const labelRe = new RegExp(`\\b(${labelAlternation})\\s*:`, "gi");
  const matches = [...region.matchAll(labelRe)];

  const dict: Record<string, string> = {};
  for (let i = 0; i < matches.length; i += 1) {
    const label = matches[i][1].toLowerCase();
    const valueStart = (matches[i].index ?? 0) + matches[i][0].length;
    const valueEnd = i + 1 < matches.length ? matches[i + 1].index ?? region.length : region.length;
    const value = clean(region.slice(valueStart, valueEnd));
    if (!(label in dict) && value) dict[label] = value;
  }
  return dict;
}

/* Title line fallback for builder, e.g. "16.7 m 2024 Sunseeker Manhattan 55".
   Takes the word after the year as the builder. */
function titleMakeFallback(text: string): string {
  const m = text.match(/\b(?:19|20)\d{2}\s+([A-Z][A-Za-z]+)/);
  return m ? m[1] : "";
}

function firstMatch(value: string, re: RegExp): string {
  const m = value.match(re);
  return m ? m[0] : "";
}

function metersFromText(value: string): number | null {
  if (!value) return null;
  const m = value.match(/([\d.,]+)\s*m(?:\s*([\d.,]+)\s*cm)?/i);
  if (!m) return null;
  const whole = Number(String(m[1]).replace(",", "."));
  const cm = m[2] ? Number(String(m[2]).replace(",", ".")) : 0;
  if (!Number.isFinite(whole)) return null;
  return m[2] ? whole + cm / 100 : whole;
}

function parseEngineHours(description: string): string {
  const m = description.match(/([\d,]+)\s*(?:engine\s*)?hours?\b/i);
  return m ? m[1].replace(/,/g, "") : "";
}

function matchValue(text: string, re: RegExp): string {
  const m = text.match(re);
  return m ? clean(m[1] ?? m[0]) : "";
}

function parseMeters(text: string, re: RegExp): number | null {
  const m = text.match(re);
  if (!m) return null;
  const whole = Number(String(m[1]).replace(",", "."));
  const cm = m[2] ? Number(String(m[2]).replace(",", ".")) : 0;
  if (!Number.isFinite(whole)) return null;
  // "14 m 6 cm" → 14.06; a bare decimal like "14.06" is already metres.
  return m[2] ? whole + cm / 100 : whole;
}

/* Extract a EUR price. Listings often show a foreign price with a euro
   conversion in parentheses, e.g. "US$2,295,000 (€1,988,916)" — we prefer the
   euro figure. If only a non-euro currency is present we still capture the
   number but flag it for the broker to confirm. */
function parsePriceEur(priceField: string, fullText: string, warnings: string[]): string {
  const digits = (value: string) => {
    const n = Number(value.replace(/[^\d]/g, ""));
    return Number.isFinite(n) && n > 0 ? String(n) : "";
  };

  // 1) Euro amount in the price field (handles the "(€…)" conversion).
  const euro = priceField.match(/(?:€|EUR)\s*([\d.,]+)/i);
  if (euro) {
    const n = digits(euro[1]);
    if (n) return n;
  }
  // 2) Euro amount anywhere in the document.
  const euroAny = fullText.match(/(?:€|EUR)\s*([\d.,]+)/i);
  if (euroAny) {
    const n = digits(euroAny[1]);
    if (n) return n;
  }
  // 3) A non-euro amount in the price field — capture but flag the currency.
  const other = priceField.match(/(?:US\$|\$|£|USD|GBP)?\s*([\d.,]{4,})/);
  if (other) {
    const n = digits(other[1]);
    if (n) {
      if (/\$|US\$|USD|£|GBP/i.test(priceField)) {
        warnings.push("Price looks like a non-euro currency — confirm the EUR amount before saving.");
      }
      return n;
    }
  }
  return "";
}

/* Map a "Tax"/"VAT" detail value (or, failing that, language in the body) to
   our VAT status enum. */
function normalizeVat(taxValue: string, fullText: string, warnings: string[]): string {
  // The Tax/VAT label sometimes sits in the header line (above "Boat Details"),
  // so fall back to scanning the whole document for it.
  const headerTax = fullText.match(/\b(?:Tax|VAT)\s*:\s*([A-Za-z ]+?)(?=\s+[A-Z][a-z]|,|\s*$)/i);
  const v = (taxValue || headerTax?.[1] || "").toLowerCase();
  if (v) {
    if (/not paid|unpaid|excl|exempt/.test(v)) return "Not Paid";
    if (/commercial/.test(v)) return "Commercial";
    if (/paid|incl/.test(v)) return "EU VAT Paid";
  }
  return parseVatStatus(fullText, warnings);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function parseLocation(text: string): string {
  const m =
    text.match(/Boat Location:\s*([A-Za-z0-9 ,.'’\-éèàûô()/]+?)(?:\s+Fuel Type|\s+Description|$)/i) ||
    text.match(/Located in\s+([A-Za-z0-9 ,.'’\-éèàûô()/]+)/i);
  return m ? clean(m[1]).replace(/\s*,\s*$/, "") : "";
}

function parseEngines(text: string): { engines: string; engineCount: number } {
  const counts = [...text.matchAll(/\(Engine\s*(\d+)\)/gi)].map((m) => Number(m[1]));
  const engineCount = counts.length ? Math.max(...counts) : 0;
  // The engine name is the "<year> <MAKE MODEL>" run immediately before
  // "(Engine 1)". Requiring a leading year keeps the section header
  // ("…Features") out of the capture.
  const nameMatch = text.match(/\d{4}\s+([A-Z][A-Za-z0-9 .\-]*?)\s*\(Engine\s*1\)/);
  const power = matchValue(text, /Power:\s*(\d+)\s*hp/i);
  const name = nameMatch ? clean(nameMatch[1]) : "";
  if (!name) return { engines: "", engineCount };
  const prefix = engineCount > 1 ? `${engineCount}× ` : "";
  const suffix = power ? ` (${power} hp)` : "";
  return { engines: `${prefix}${name}${suffix}`.trim(), engineCount };
}

function parseCabins(text: string): string {
  const direct = text.match(/(\d+)\s*cabins?/i);
  if (direct) return direct[1];
  // Infer from equipment headings (MASTER CABIN / GUEST CABIN).
  const cabinSections = (text.match(/\b(MASTER|GUEST|VIP|OWNER)\s+CABIN\b/gi) ?? []).length;
  return cabinSections > 0 ? String(cabinSections) : "";
}

function parseVatStatus(text: string, warnings: string[]): string {
  const lower = text.toLowerCase();
  const inclusive = /(including vat|incl\.?\s*vat|vat paid|ttc|toutes taxes)/.test(lower);
  const exclusive = /(excl\.?\s*vat|ex\s*vat|plus vat|hors taxes|\bht\b|vat not paid)/.test(lower);
  if (inclusive && exclusive) {
    warnings.push("VAT status is ambiguous in the PDF — defaulting to EU VAT Paid, please confirm.");
    return "EU VAT Paid";
  }
  if (inclusive) return "EU VAT Paid";
  if (exclusive) return "Not Paid";
  if (/commercial/.test(lower)) return "Commercial";
  return "Unknown";
}

function parseDescription(text: string): string {
  // The marketing copy sits between the "Description" heading and the
  // structured "Information & Features" / "Additional Information" section.
  const m = text.match(/Description\s+([\s\S]*?)\s+(?:Information & Features|Additional Information)/i);
  if (!m) return "";
  return cleanBlock(m[1]);
}

function parseEquipment(text: string): string {
  // Everything from the structured spec section onward, minus the legal
  // disclaimer boilerplate and trailing page numbers.
  const start = text.search(/Information & Features/i);
  if (start === -1) return "";
  let block = text.slice(start);
  block = block.replace(
    /The Company offers the details of this vessel in good faith[\s\S]*?without notice\.?/gi,
    "",
  );
  block = block.replace(/\bAdditional Information\b/gi, "");
  return cleanBlock(block);
}

function normalizeCondition(value: string): string {
  const v = value.toLowerCase();
  if (v.includes("new")) return "New";
  if (v.includes("refit")) return "Refit";
  if (v.includes("project")) return "Project / needs work";
  if (v.includes("used")) return "Used";
  return CONDITION_OPTIONS.includes(value) ? value : "";
}

function normalizePropulsion(fuelType: string, engineCount: number): string {
  if (fuelType.includes("diesel")) return engineCount >= 2 ? "Twin diesel" : "Diesel";
  if (fuelType.includes("electric")) return "Electric";
  if (fuelType.includes("hybrid")) return "Hybrid";
  if (fuelType.includes("petrol") || fuelType.includes("gas")) return "Motor";
  if (engineCount >= 1) return "Motor";
  return PROPULSION_OPTIONS.includes(fuelType) ? fuelType : "";
}

function normalizeWhitespace(text: string): string {
  return text.replace(/ /g, " ").replace(/[ \t]+/g, " ").replace(/\s*\n\s*/g, "\n").trim();
}

function clean(value: string): string {
  return value
    .replace(/\s*\n\s*/g, " ")
    // rejoin words hyphenated across a line break ("Pyrénées- Orientales")
    .replace(/([A-Za-zÀ-ÿ])-\s+([A-Za-zÀ-ÿ])/g, "$1-$2")
    .replace(/\s{2,}/g, " ")
    .replace(/\s+([,.;:])/g, "$1")
    .trim();
}

/* clean() for long prose blocks: also drops the stray per-page numbers the
   export leaves behind (e.g. a lone "3" between sections). Kept separate so
   it never touches short field values like a model name ("Rebel 47"). */
function cleanBlock(value: string): string {
  return clean(value.replace(/\s+\b\d{1,2}\b(?=\s|$)/g, " "));
}

/* ---- Embedded JPEG extraction (Node) ----------------------------------- */

export interface ExtractedPdfImage {
  /** Raw JPEG bytes, directly writable as a .jpg. */
  data: Uint8Array;
  bytes: number;
}

/* Boats.com exports embed each photo as a DCTDecode (JPEG) image XObject,
   whose stream bytes are a complete JPEG (SOI…EOI). We slice those out
   directly — no decoding needed — and skip non-JPEG assets (logos are tiny
   FlateDecode PNGs). De-duplicates identical streams. */
export function extractPdfJpegs(buffer: Uint8Array): ExtractedPdfImage[] {
  const latin1 = Buffer.from(buffer).toString("latin1");
  const images: ExtractedPdfImage[] = [];
  const seen = new Set<string>();
  const filterRe = /\/DCTDecode/g;
  let match: RegExpExecArray | null;

  while ((match = filterRe.exec(latin1)) !== null) {
    const streamIdx = latin1.indexOf("stream", match.index);
    if (streamIdx === -1) continue;
    let start = streamIdx + "stream".length;
    if (latin1[start] === "\r") start += 1;
    if (latin1[start] === "\n") start += 1;
    if (!(buffer[start] === 0xff && buffer[start + 1] === 0xd8)) continue; // not a JPEG SOI

    let end = start + 2;
    while (end < buffer.length - 1 && !(buffer[end] === 0xff && buffer[end + 1] === 0xd9)) {
      end += 1;
    }
    end += 2; // include the EOI marker
    if (end > buffer.length) continue;

    const data = buffer.slice(start, end);
    if (data.length < 1024) continue; // ignore thumbnails / icons

    const key = `${start}:${end}:${data.length}`;
    if (seen.has(key)) continue;
    seen.add(key);
    images.push({ data, bytes: data.length });
  }

  return images;
}
